language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

matrix:
  fast_finish: true
#  allow_failures:
#    - python: 3.5
#      env: DJANGO=dev TEST_SUITE=django
install:
  - pip install tox tox-travis wheel codecov "coverage<4"
before_script:
  - pip freeze
script:
  - if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi
  - tox
after_success:
  - codecov -e DJANGO


