language: python
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
cache:
  directories:
    - "$HOME/.cache/pip"
python:
  - "2.7"
 # - "3.3"
  - "3.4"
  - "3.5"
 # - "pypy"
#env:
#  - DJANGO="1.7"
#  - DJANGO="1.8"
#  - DJANGO="1.9"
#  - DJANGO="1.10"
#  - CELERY="3"
#  - CELERY="4"
#  - FLASK="10"
#  - FLASK="11"
#  - FLASK="12"

matrix:
  fast_finish: true
#  allow_failures:
#    - python: 3.5
#      env: DJANGO=dev TEST_SUITE=django
install:
  - pip install tox tox-travis wheel codecov "coverage<4"
before_script:
  - pip freeze
script:
  - tox
after_success:
  - codecov -e DJANGO


